# Implementation of Fisheries Research Agenda
For effective implementation of the National Fisheries and Aquaculture Research Agenda an appropriate framework has to be established based on key players. The framework will ensure that each key player, plays the role which it has comparative advantage, hence, leading to proper research development, consolidation of research findings and dissemination. 

The Ministry of livestock and Fisheries (Fisheries Sector) will liaison not only with the research Institutions and other related stakeholders but also at the Local Government Authorities level (Ward levels). According to the local government reforms, the LGAs have a role in the implementation of the research activities within their areas of jurisdiction and have roles of identifying areas which require further research in their areas.

Despite, research Institutions having their own legislative mandate on matters pertaining to fisheries and aquaculture research, the Ministry of Livestock and Fisheries (Fisheries Sector) will develop Regulations which will guide and ensure smooth implementation of the Research Agenda.

## Coordination of research activities
The Ministry responsible for the National Fisheries\index{fisheries} and Aquaculture Research Agenda has a mandate to implement it and ensuring that the fisheries and national strategic objectives are achieved through scientific information derived from research. Therefore, the Ministry has a role of determining the review of the policy and legislation based on research outcomes.

On the other hand, the Ministry of Livestock and Fisheries will coordinate all research activities related to fisheries and Aquaculture Sectors and it will set up the terms of reference for implementation and dissemination of research findings in the country via responsible department and principally through;

i. Develop proper modalities for collection and dissemination of fisheries and aquaculture research finding from research institutions e.g. utilization of research findings through policy briefs
i. Organize regular scientific fora with researchers and fisheries stakeholders’
i. National exhibitions,
i. Mass media such as radio and television programmes, magazines and newsletters,
i. Establishment of research websites backed by an e-library and
i. A compiled dataset will be submitted to COSTECHas National depository.


## Collaboration and linkages
The Ministry responsible for fisheries\index{fisheries} and aquaculture\index{aquaculture} is mandated to coordinate fisheries and aquaculture research and fisheries and aquaculture developmental activities countrywide. Generally, the ministry has a role of soliciting funds by writing projects from friends of the Ministry and Government e.g. the ongoing SWIO Fish Project. 

Furthermore, it is the responsibility of the Ministry in collaboration with COSTECH and TAFIRI to offer funds for implementation of research activities. Additionally, LGAs have a responsibility to provide funds for carryout fisheries research and disseminate research findings to stakeholders within their areas of jurisdiction. 

At Ministerial level, the Tanzania Fisheries Research Institute (TAFIRI) is mandated to carryout fisheries and aquaculture research and other related research in the country as stipulated in Tanzania Fisheries Research Institute Act 2016 and as per National Fisheries and Aquaculture Research Agenda. TAFIRI has also a role of collaborating with other research Institutions in carrying out any research activity and responsibility of issuing all research permits to any person or Institution interested in carrying out fisheries research in Tanzania. Also it has a role of writing research proposal and submit them to various research donors for funding.

The National Commission for Science and Technology (COSTECH), the principal advisory organ to the Government in all matters pertaining to scientific research, technological development and coordination of research activities in the country. Also has a role of providing advice on the course of implementation of the Agenda at the same time providing funds for implementation of the Agenda.

The training Institutions which offer academic training of which fisheries research is part of their training, have a responsibility of implementing the Agenda by providing research themes and areas of priorities to Masters, PhD Students and also to other interested individuals. Also they have a role of delivering research findings including policy briefs for use by the Ministry.

The Non–Governmental Organizations such as WWF, EU, IUCN, AU-IBAR etc. have a role of solicit and provide funds for the implementation of the National Fisheries and Aquaculture Research Agenda in whatsoever way, either by doing or by providing funds to research Institutions and interested individuals.

Furthermore, the Ministry of Livestock and fisheries (Fisheries Sector) will collaborate closely with research institutions and other related stakeholders to ensure effective implementation of the National Fisheries and Aquaculture Research Agenda 2020-2025. These institutions include but not limited to LVFO, UDSM, SUA, UDOM, IMS, Zanzibar Fisheries Department, MPRU, DSFA, University of Bergen, Tokyo Institute of Technology, WWF, WB, WIOMSA, TMA, SADC, SIDA/SAREC, IDRC, EU, KMFRI and NAFIRRI. Other collaborators include; Fishers, Fish Farmers, Processors, Traders, Consumers; Non-State Actors (NGOs, CBOs, CSOs); and Private Sectors.

